@backend_HostAddress = http://172.20.49.43:5076

GET {{backend_HostAddress}}/IotData/average/your_device_id/100/10
Accept: application/json

###

GET {{backend_HostAddress}}/IotData/current/your_device_id
Accept: application/json

###
